__author__ = 'Zhifei Chen'

Pysonar_Dir = 'XXX'
Subject_Dir = 'XXX'
Data_Dir = 'XXX'

Project_Names = [
# 'TheAlgorithms',
# 'youtube-dl',
'models',
'nvbn',
# 'django',
'flask',
'keras',
'httpie',
'ansible',
'transformers',
'scikit-learn',
'requests',
# 'core',
'scrapy',
'you-get',
'face_recognition',
# 'superset',
# 'cpython',
'faceswap',
'manim',
# 'shadowsocks',
# 'fastapi',
'XX-Net',
# 'localstack',
'12306',
'pandas',
# 'sentry',
'bert',
'certbot',
'DeepFaceLab',
# 'rich',
'sherlock',
'Real-Time-Voice-Cloning',
'Detectron',
'gym',
# 'geekcomputers',
'HanLP',
'YouCompleteMe',
'compose',
'mitmproxy',
'pipenv',
# 'airflow',
'ItChat',
'black',
'django-rest-framework',
# 'algo',
'pytorch-tutorial',
# 'spaCy',
'sqlmap',
'Mask_RCNN',
'tornado',
'ML-From-Scratch',
'algorithms',
'python-fire',
'redash',
'tqdm',
'glances',
'hosts',
'celery',
'numpy',
'detectron2',
'magenta',
'spleeter',
'examples',
'locust',
'ray',
'jumpserver',
# 'Paddle',
# 'python-telegram-bot',
'poetry',
'mmdetection',
'bokeh',
'pytorch-CycleGAN-and-pix2pix',
'sanic',
'pyspider',
'ipython',
'streamlit',
'cookiecutter',
'dash',
'luigi',
'labelImg',
'PySnooper',
'zipline',
'wechat_jump_game',
'zulip',
# 'pytorch-lightning',
# 'matplotlib',
'diagrams',
'avatarify-python',
'kivy',
'fairseq',
'jax',
'fabric',
'InstaPy',
'prophet',
'magic-wormhole',
# 'cryptography',
'Ciphey',
'PySyft',
'RsaCtfTool',
'pycrypto',
'laravel-hashids',
# 'pynacl',
'paramiko',
'PaddleOCR',
'autojump'
]

Domain_Dict = {
    'Cryptography':('magic-wormhole','Ciphey','PySyft','RsaCtfTool','pycrypto','laravel-hashids','paramiko'),
    'Data Processing': ('algorithms','redash','numpy','pandas','scikit-learn','bokeh','dash','ipython','diagrams'),
    'Web':('django-rest-framework','flask','sanic','streamlit','zulip','sherlock','pyspider','scrapy','requests','tornado'),
    'Security Tool':('jumpserver','certbot','mitmproxy','sqlmap','hosts','XX-Net'),
    'Command-line Tool':('cookiecutter','python-fire','httpie','glances','nvbn','you-get','12306','tqdm','autojump'),
    'Computer Vision':('pytorch-CycleGAN-and-pix2pix','Mask_RCNN','mmdetection','labelImg'),
    'Machine Learning':('face_recognition','avatarify-python','Real-Time-Voice-Cloning','faceswap','spleeter','ML-From-Scratch',
                        'prophet','Detectron','detectron2','jax','DeepFaceLab','keras','magenta','gym','PaddleOCR','examples','fairseq','models','pytorch-tutorial'),
    'Python Management':('black','pipenv','poetry','YouCompleteMe','PySnooper'),
    'NLP':('bert','HanLP','transformers'),
    'Application Development':('zipline','ray','kivy','ItChat','ansible','fabric','InstaPy','wechat_jump_game'),
    'Others':('celery','locust','manim','compose','luigi')
}